title: Evropští zápasníci MMA v organizaci UFC
baseURL: https://tender-leavitt-e2787b.netlify.com/
languageCode: cs-cz
publishDir: public

menu:
  main:
    - name: Homepage
      url: /
      weight: 10
    - name: Články
      identifier: post
      url: /post/
      weight: 20

params:
  description:
  authors: K. Fialová, L. Večeřová, M. Velebová

